### ISSUE TITLE
Add SNesoid

### ISSUE THREAD

**Issue by Kcchouette** [LeifAndersen/AndroidEmu#2]
In the tarball, we can found snesoid, can you add it to your repositories, please ?  
http://sourceforge.net/projects/androidemu/files/SNesoid.tar.gz/download or add this fork https://github.com/Pretz/SNesoid  
Thanks

**Comment by Kcchouette** [comment]
Please add too http://sourceforge.net/projects/n64oid/

**Comment by LeifAndersen** [comment]
I have added snesoid.

**Comment by LeifAndersen** [comment]
Added N64oid.

**Comment by LeifAndersen** [comment]
I'm also going to add you as a contributer to this project, so you can add stuff too.
